<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQpDJeWG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQpDJeWG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQpDJeWG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQpDJeWG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQpDJeWG\App_KernelDevDebugContainer([
    'container.build_hash' => 'QpDJeWG',
    'container.build_id' => '4dd461e5',
    'container.build_time' => 1652709085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQpDJeWG');
